
//////////////////////////////////////////////////////////////////////////////////////////
//  This is a complete determination of the quartic and quintic points on X1(26)
//////////////////////////////////////////////////////////////////////////////////////////
 
/****************************************************************************** 
 Here is a summary of the argument.
 
 X_1(26) has genus 10, and rank 0.
 The torsion subgroup is [133, 1995],
 and is generated by differences of rational points.

 There are phi(26)/2 = 12 rational cusps and 0 quadratic or cubic cusps, 2 sextic cusps.

 Computing the inverse image of Abel-Jacobi succeeds. 
 It is slow to do this directly, so instead, we work mod 3, and note that
 there are 12 F_3 points, 0 F_9 points, and 16 F_27 points, 12 F_81 points. 

 We compute that the images of the 12 F_81 points under Abel--Jacobi
 do not meet the reduction of the global torsion. Similarly with 
 combinations of the 16 F_27 points and 12 F_3 points.
 
 One subtlety of this case is that it greatly speeds things up to work
 on a singular model.
 
******************************************************************************/

  N := 26; 

  
  //////////////////////////////////////////////////////////////////////////////////////////
  // Input the homebrewed functions 
  //////////////////////////////////////////////////////////////////////////////////////////
  
  load "functions.m";

  
  //////////////////////////////////////////////////////////////////////////////////////////
  // Equations for X1(26), from Derickx--Sutherland
  //////////////////////////////////////////////////////////////////////////////////////////
  
  F := Rationals();
  P<[t]> := ProjectiveSpace(F,9);       
  A2<x,y> := AffineSpace(F,2);

  X:=Curve(A2,y^6 + (3*x^2 + 4*x - 2)*y^5 + (3*x^4 + 10*x^3 - 9*x + 1)*y^4 + (x^6 + 7*x^5 + 8*x^4 - 14*x^3 - 11*x^2 + 6*x)*y^3 + (x^7 + 4*x^6 - x^5 - 13*x^4 + 2*x^3 + 10*x^2 - x)*y^2 - (x^6 - 7*x^4 - 4*x^3 + 2*x^2)*y - x^4 - x^3);
  Xp := ProjectiveClosure(X);

  
  //////////////////////////////////////////////////////////////////////
  // Compute the local torsion bound
  //////////////////////////////////////////////////////////////////////   
/*
//  for p in [q : q in PrimesUpTo(40) | not q in PrimeDivisors(2*N) ] do
  torsData := {@@};
  for p in [3,5 ] do     
      invs := Invariants(ClassGroup(Curve(Reduction(X,p))));
      torsData := torsData join {@invs@};
      <p,invs>;
  end for;

  // 3 [ 665, 1995, 0 ]
  // 5 [ 7, 133, 29925, 0 ]      

    "The rational torsion subgroup is a subgroup of", torsBound(torsData); ; // [133, 1995]
*/  
  
  ////////////////////////////////////////////////////////////////////////
  // Compute the known small degree points
  ////////////////////////////////////////////////////////////////////////
    
  // Hard code as much as possible, since Magma changes
  // how it orders the output of "Support" mod different primes
  
  basePt := [-1 , 0 , 1];
  
  // mostly singular
  pts := 
  [
    [  0, 1, 0 ],
    [  0, 0, 1 ],
    [ -1, 0, 1 ],
    [  0, 1, 1 ],
    [  1, 0, 0 ],
    [ -1, 1, 1 ],
    [ -1, 1, 0 ]
  ];    
    
  // Verify that these generate the torsion  
  p := 3;
  Cp<[T]> := Curve(Reduction(Xp,p));
    pic,mPic := ClassGroup(Cp);    
  basePt := &+Places(Cp![-1,0,1]);
  divs := {@
         &+Places(Cp!pt) - Degree(&+Places(Cp!pt))*basePt
         : pt in pts @} ;  
  
  global, mGlobal := 
     sub<pic | [(Inverse(mPic))(divs[i]) : i in [1..#divs]]>;  
  Invariants(global); // [ 133, 1995 ]    
   

  //////////////////////////////////////////////////////////////////////
  // Compute the image of Abel--Jacobi mod 3, Quartic
  //////////////////////////////////////////////////////////////////////  
    
  "There are", [#Places(Cp,i) : i in [1..5]], "places of degree 1, 2, 3, 4 and 5 over F_3"; // [ 12, 0, 16, 12, 48 ]   
    // the 12 degree 1 points lift to Q so we compute with the 16 cubic points, and 12 quartic
    
  validQuarticImages := {@@};
  for pl in Places(Cp,4) do
      D := Divisor(pl) - Degree(pl)*basePt;
      if Inverse(mPic)(D) in global then
        validQuarticImages := 
        validImages join {@Inverse(mPic)(D)@};
      end if;
  end for;
  "The rational places all lift to Q, and",  #validQuarticImages, "of the other places are in the image of Abel--Jacobi"; // 0
//0
moreValidQuarticImages := {@@};
  for p in Places(Cp, 3) do
    for q in Places(Cp, 1) do 
      D := Divisor(p) + Divisor(q) - 4*basePt;
      if Inverse(mPic)(D) in global then
        moreValidQuarticImages := 
        moreValidQuarticImages join {@Inverse(mPic)(D)@};
      end if;
    end for;
  end for;
  "There are", #moreValidQuarticImages, "of the other places (coming from two quadratics) in the image of Abel--Jacobi"; 
//0

  moreValidQuarticImages := {@@};
  for p1 in Places(Cp, 1) do
    for p2 in Places(Cp, 1) do 
        for p3 in Places(Cp, 1) do 
            for p4 in Places(Cp, 1) do 
              D := Divisor(p1) + Divisor(p2) + Divisor(p3) + Divisor(p4) - 4*basePt;
              if Inverse(mPic)(D) in global then
                moreValidQuarticImages := 
                moreValidQuarticImages join {@Inverse(mPic)(D)@};
              end if;
            end for;
        end for;
    end for;
  end for;
  "There are", #moreValidQuarticImages, "of the other places (coming from a 4 degree 1 points) in the image of Abel--Jacobi"; 
 //1365
 //this is 15 choose 4 


 //////////////////////////////////////////////////////////////////////
  // Compute the image of Abel--Jacobi mod 3, Quintic
  //////////////////////////////////////////////////////////////////////  

  validQuinticImages := {@@};
  for pl in Places(Cp,5) do
      D := Divisor(pl) - Degree(pl)*basePt;
      if Inverse(mPic)(D) in global then
        validQuinticImages := 
        validQuinticImages join {@Inverse(mPic)(D)@};
      end if;
  end for;
  "The rational places all lift to Q, and",  #validQuinticImages, "of the other places (coming from a quintic point) are in the image of Abel--Jacobi"; 
//0

   validQuinticImages := {@@};
  for p in Places(Cp, 4) do
    for q in Places(Cp, 1) do 
      D := Divisor(p) + Divisor(q) - 5*basePt;
      if Inverse(mPic)(D) in global then
        validQuinticImages := 
        validQuinticImages join {@Inverse(mPic)(D)@};
      end if;
    end for;
  end for;
  "There are", #validQuinticImages, "of the other places (coming from 1 quartic and 1 rational) in the image of Abel--Jacobi"; 
//0


 moreValidQuinticImages := {@@};
  for p1 in Places(Cp, 3) do
    for p2 in Places(Cp, 1) do 
        for p3 in Places(Cp, 1) do 
              D := Divisor(p1) + Divisor(p2) + Divisor(p3) - 5*basePt;
              if Inverse(mPic)(D) in global then
                moreValidQuinticImages := 
                moreValidQuinticImages join {@Inverse(mPic)(D)@};
              end if;
        end for;
    end for;
  end for;
  "There are", #moreValidQuinticImages, "of the other places (coming from a 1 degree 3 point, 2 degree 1 points) in the image of Abel--Jacobi"; 
//0


moreValidQuinticImages := {@@};
  for p1 in Places(Cp, 1) do
    for p2 in Places(Cp, 1) do 
        for p3 in Places(Cp, 1) do 
            for p4 in Places(Cp, 1) do
              for p5 in Places(Cp, 1) do 
                D := Divisor(p1) + Divisor(p2) + Divisor(p3) + Divisor(p4) + Divisor(p5) - 5*basePt;
                if Inverse(mPic)(D) in global then
                  moreValidQuinticImages := 
                  moreValidQuinticImages join {@Inverse(mPic)(D)@};
                end if;
              end for;
            end for;
        end for;
    end for;
  end for;
  "There are", #moreValidQuinticImages, "of the other places (coming from a 4 degree 1 points) in the image of Abel--Jacobi"; 
// n + k -1 choose k (picking k things from n with repitition)
 //4368 
  //this is 12 + 5 -1 choose 5 = 16 choose 5 = 4386 
 

